import type { Metadata } from "next";
import { Inter_Tight } from "next/font/google";
import "./globals.scss";
import Header from "@/components/common/Header/Header";
import Footer from "@/components/common/Footer/Footer";
import BackgroundLines from "@/components/common/BackgroundLines/BackgroundLines";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const interTight = Inter_Tight({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={interTight.className}>
        <Header />

        <BackgroundLines />

        {children}
        <Footer />
      </body>
    </html>
  );
}
